name: tap_payment
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  shared_preferences: ^2.0.13
  responsive_sizer: ^3.0.5+1
  uuid: ^3.0.6
  auto_size_text: ^3.0.0
  another_flushbar: ^1.10.28
  camera: ^0.9.4+14
  extended_image: ^6.0.1

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
